### ISSUE TITLE
tacoplot_stack relative abundances not a fraction of 1 or 100%

### ISSUE THREAD

**Issue by slambrechts** [LebeerLab/tidytacos#59]
Hi,

When I want to use `tacoplot_stack  ` like so:

`tacoplot_stack(tidy_physeq_rarefied, x = Protocol2)
`

The y-axis is not correctly adjusted to range from 0 to 1 (0% to 100%), so representation of relative abundances is not comparable across x-axis categories.

Anything I'm doing wrong here?

**Comment by TheOafidian** [comment]
Is it possible that the 'Protocol2' column does not have unique values (a warning is likely raised too)? 
If that is the case using x=Protocol2 will stack all samples with similar Protocol2 on top of eachother. 

If you want to compare relative abundaces between these groups of samples you could maybe do something along the lines of:

```
tidy_physeq_rarefied %>%
select_samples(sample_id,  Protocol2) %>%
aggregate_samples() %>%
tacoplot_stack(x=Protocol2)
```

**Comment by slambrechts** [comment]
Ok yes, that was indeed what I was trying to do, and your solution works! Thank you
